chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "chatbot"
urlpatterns = [
    path("home_bot", views.home, name='home'),
    path("speech_to_text/", views.speech_to_text, name='speech_to_text'),
 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tutorial.urls')),
    path('',include('speech_bot.urls')),
]

chatbot/views.py
from django.shortcuts import render
import pyttsx3
import speech_recognition as sr  # importing speech recognition package from google api
# from pygame import mixer
import playsound  # to play saved mp3 file
from gtts import gTTS  # google text to speech
import os  # to save/open files
import wolframalpha  # to calculate strings into formula, its a website which provides api, 100 times per day
from selenium import webdriver  # to control browser operations






# Create your views here.

def home(request):
    return render(request, 'chatbot/home_bot.html')
num = 1

def assistant_speaks(output):
    global num
    num += 1
    print("PerSon : ", output)
    toSpeak = gTTS(text=output, lang='en-US', slow=False)
    file = str(num) + ".mp3"
    toSpeak.save(file)
    # mp3_fp = BytesIO()
    # toSpeak = gTTS(output, 'en', slow=False)
    # toSpeak.write_to_fp(mp3_fp)
    # os.system("D:\PeRSon\\audio\spoken.mp3")
    '''mixer.init()
    mixer.music.load('D:\PeRSon\\audio\spoken.mp3')
    mixer.music.play()
    time.sleep(5)
    mixer.music.stop()'''
    # song = AudioSegment.from_file(mp3_fp, format="mp3")
    # playsound.playsound(mp3_fp)
    playsound.playsound(file, True)
    os.remove(file)


def get_audio():
    r = sr.Recognizer()
    audio = ''
    with sr.Microphone() as source:
        print("Speak...")
        audio = r.listen(source, phrase_time_limit=5)
    print("Stop.")
    try:
        text = r.recognize_google(audio, language='en-US')
        print("You : ", text)
        return text
    except:
        assistant_speaks("Could not understand your audio, PLease try again!")
        return 0


def search_web(input):
    driver = webdriver.Firefox()
    driver.implicitly_wait(1)
    driver.maximize_window()
    if 'youtube' in input.lower():
        assistant_speaks("Opening in youtube")
        indx = input.lower().split().index('youtube')
        query = input.split()[indx + 1:]
        driver.get("http://www.youtube.com/results?search_query=" + '+'.join(query))
        return

    elif 'wikipedia' in input.lower():
        assistant_speaks("Opening Wikipedia")
        indx = input.lower().split().index('wikipedia')
        query = input.split()[indx + 1:]
        driver.get("https://en.wikipedia.org/wiki/" + '_'.join(query))
        return
    else:
        if 'google' in input:
            indx = input.lower().split().index('google')
            query = input.split()[indx + 1:]
            driver.get("https://www.google.com/search?q=" + '+'.join(query))
        elif 'search' in input:
            indx = input.lower().split().index('google')
            query = input.split()[indx + 1:]
            driver.get("https://www.google.com/search?q=" + '+'.join(query))
        else:
            driver.get("https://www.google.com/search?q=" + '+'.join(input.split()))
        return


def open_application(input):
    if "chrome" in input:
        assistant_speaks("Google Chrome")
        os.startfile('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe')
        return
    elif "firefox" in input or "mozilla" in input:
        assistant_speaks("Opening Mozilla Firefox")
        os.startfile('C:\Program Files\Mozilla Firefox\\firefox.exe')
        return
    elif "word" in input:
        assistant_speaks("Opening Microsoft Word")
        os.startfile('C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Office 2013\\Word 2013.lnk')
        return
    elif "excel" in input:
        assistant_speaks("Opening Microsoft Excel")
        os.startfile('C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Office 2013\\Excel 2013.lnk')
        return
    else:
        assistant_speaks("Application not available")
        return


def process_text(input):
    try:
        if "who are you" in input or "define yourself" in input:
            speak = '''Hello, I am Person. Your personal Assistant.
            I am here to make your life easier. 
            You can command me to perform various tasks such as calculating sums or opening applications'''
            assistant_speaks(speak)
            return
        elif "who made you" in input or "created you" in input:
            speak = "I have been created by Alex."
            assistant_speaks(speak)
            return
        elif "calculate" in input.lower():
            app_id = "E46YXW-T5LG6RT7K7"
            client = wolframalpha.Client(app_id)
            indx = input.lower().split().index('calculate')
            query = input.split()[indx + 1:]
            res = client.query(' '.join(query))
            answer = next(res.results).text
            assistant_speaks("The answer is " + answer)
            return
        elif 'open' in input:
            open_application(input.lower())
            return
        elif 'search' in input or 'play' in input:
            search_web(input.lower())
            return
        else:
            assistant_speaks("I can search the web for you, Do you want to continue?")
            ans = get_audio()
            if 'yes' in str(ans) or 'yeah' in str(ans):
                search_web(input)
            else:
                return
    except Exception as e:
        print(e)
        assistant_speaks("I don't understand, I can search the web for you, Do you want to continue?")
        ans = get_audio()
        if 'yes' in str(ans) or 'yeah' in str(ans):
            search_web(input)


def speech_to_text(request):
    data = request.POST.get('record')
    import speech_recognition as sr

    # get audio from the microphone
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Speak:")
        audio = r.listen(source)
    try:
        output = " " + r.recognize_google(audio)
    except sr.UnknownValueError:
        output = "Could not understand audio"
    except sr.RequestError as e:
        output = "Could not request results; {0}".format(e)
    data = output
    while (1):
        assistant_speaks("What can i do for you?")
        text = get_audio()
        if text == 0:
            continue
        # assistant_speaks(text)
        if "exit" in str(text) or "bye" in str(text) or "go " in str(text) or "sleep" in str(text):
            assistant_speaks('Ok bye, Alex.')
            break
        text = text.lower()
        process_text(text)
    return render(request, 'chatbot/speech_to_text.html', {'data':'See ya later !'})

templates/chatbot/home_bot.html
<!DOCTYPE html>
<html>
<head>
<style>
.button {
  background-color: #ddd; /* Green */
  border: none;

  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 25px;
}


.button5 {font-size: 24px;}


.project_name {
  text-shadow: 2px 2px #FF0000;
  font-size:50px;
}
.my_name {
  text-shadow: 2px 2px #FF0000;
  font-size:50px;
}
</style>
</head>
<body>

<center>
<button class="button button5"><a href="{% url 'chatbot:speech_to_text' %}">Speech to text</a> </button>

</center>



<center><h1 class="project_name">Speech Recognition Project With Django</h1>
<h4 class="my_name">By Sachin Pawar</h4>
</center>

</body>







</html>

templates/chatbot/speak.html
<html>
{% load static %}
&emsp;&emsp;&emsp;<a href="{% url 'chatbot:home' %}"><h1>Home</h1></a>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link href="{% static 'main/css/main.css' %}" rel="stylesheet" />
  </head>
  <body bgcolor="">
    <div class="s130">
      <form method="post">
        {% csrf_token %}
        <div class="inner-form">
          <div class="input-field first-wrap">
            <div class="svg-wrapper">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
              </svg>
            </div>
            <input id="search" type="text" name="search" placeholder="Text to speech" />
          </div>
          <div class="input-field second-wrap">
            <button class="btn-search"  type="button">Speak</button>
          </div>
        </div>

      </form>
      {{data}}
    </div>
    <script src="{% static 'main/js/extention/choices.js' %}"></script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/chatbot/speech_to_text.html
<!DOCTYPE html>
<html>
<head>
<style>
body  {

  background-color: #cccccc;
}


.button {
  background-color: #0020C2;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 25px;
}


.button5 {font-size: 24px;}
</style>
</head>
<body>
<center>
    <br/>
    <br/>
    <br/>
    <h1><a href="{% url 'chatbot:home' %}">Home</a> </h1>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
<form method="post">
    {% csrf_token %}
<input type="hidden" name="record">
<button class="button button5">Record</button>
</form>
<br/>
<br/>
<br/>
    <h1 style="color:red;"> {{data}}</h1>
    </center>
</body>
</html>