chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "chatbot"
urlpatterns = [
    path("home_bot", views.home, name='home'),
    path("speech_to_text/", views.speech_to_text, name='speech_to_text'),
 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

speech_bot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "speech_bot"
urlpatterns = [
    path("home_bot", views.home, name='home'),
    path("speech_to_text/", views.speech_to_text, name='speech_to_text'),

 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tutorial.urls')),
    path('',include('speech_bot.urls')),
]

speech_bot/models.py
from django.db import models

# Create your models here.

speech_bot/views.py
import threading

from speech_bot.text_processing import process_text, assistant_speaks, chatbot_response
from django.shortcuts import render
from tutorial.decorators import pacient_and_admin_only
# from key import b71542370a6247d493860e6b01d0d713
import speech_recognition as sr  # importing speech recognition package from google api

@pacient_and_admin_only
def home(request):
    return render(request, 'speech_bot/home_bot.html')

def thread_loop(request, r):
    with sr.Microphone() as source:
        while (1):
            try:
                print('Listening ...')
                audio = r.listen(source)

                text = r.recognize_google(audio, language='en-US')

                res, intent = chatbot_response(text)
                print(intent)
                if intent == 'goodbye':
                    assistant_speaks(res)
                    break
                text = text.lower()
                print('You: ' + text)
                if 'emma' in text:
                    text_split = text.split('emma ')
                    text = text_split[1]
                    res, intent = chatbot_response(text)
                    if res != "":
                        assistant_speaks(res)
                    print('intent: ' + intent)
                    text = text.lower()
                    process_text(text, intent, request)
            except:
                continue

@pacient_and_admin_only
def speech_to_text(request):
    r = sr.Recognizer()
    threadTalkLoop = threading.Thread(target=thread_loop, kwargs={'request':request, 'r':r})
    threadTalkLoop.start()
    return render(request, 'speech_bot/home_bot.html', {'data': 'See ya later !'})

templates/speech_bot/home_bot.html
{% extends 'website/base.html' %}

<!DOCTYPE html>

{% block content %}
<style>
.button {
  background-color: #ddd; /* Green */
  border: none;

  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 25px;
}


.button5 {font-size: 24px;}


.project_name {
  text-shadow: 2px 2px #FF0000;
  font-size:50px;
}
.my_name {
  text-shadow: 2px 2px #FF0000;
  font-size:50px;
}
</style>
</head>
<body>

<center>
<button class="button button5"><a href="{% url 'speech_bot:speech_to_text' %}">Try now !</a> </button>

</center>

<h1 class="project_name">What can our Emma (alpha version) do for you?</h1>
    <ul>
<ol>
   <b> <li>Start by saying "Emma" + command</li></b>
  <li>Monitorize your illness and provide valuable feedback</li>
  <li>Can improve and strengthen health condition</li>
  <li>It uses Machine Learning for intent recognition</li>
  <li>Some of the best features:<br>
        <ul>
  <li>Can bring the individual up to date with the latest news in all over the world</li>
  <li>Plan a google calendar event and we set it up accordingly</li>
  <li>Wikipedia module: ask anything about anything</li>
  <li>Movie recommendation + scraping the best movies out there for you</li>
  <li>Discussion module: the chat can not be more real than this.
                        <ol><li> Get feedback based on what you say</li>
                        <li>Sentiment recognition. We take care of our clients.</li>
                        <li> Intelligent Google results scraping when there's a problem affecting you</li>
                        <li> No repeated solutions ! Get always diversed information</li></ol></li>
  <li>It can intelligently surf the web for you (keyword detection)</li>
  <li>It can open various browser(Chrome, Mozilla), applications (Word, Excel, etc), search for a song(On Youtube)</li>
</ul>
</li>
</ol>
</ul>






{% endblock content %}

templates/speech_bot/speak.html
<html>
{% load static %}
&emsp;&emsp;&emsp;<a href="{% url 'speech_bot:home' %}"><h1>Home</h1></a>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link href="{% static 'main/css/main.css' %}" rel="stylesheet" />
  </head>
  <body bgcolor="">
    <div class="s130">
      <form method="post">
        {% csrf_token %}
        <div class="inner-form">
          <div class="input-field first-wrap">
            <div class="svg-wrapper">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
              </svg>
            </div>
            <input id="search" type="text" name="search" placeholder="Text to speech" />
          </div>
          <div class="input-field second-wrap">
            <button class="btn-search"  type="button">Speak</button>
          </div>
        </div>

      </form>
      {{data}}
    </div>
    <script src="{% static 'main/js/extention/choices.js' %}"></script>
  </body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/speech_bot/speech_to_text.html
<!DOCTYPE html>
<html>
<head>
<style>
body  {

  background-color: #cccccc;
}


.button {
  background-color: #0020C2;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 25px;
}


.button5 {font-size: 24px;}
</style>
</head>
<body>
<center>
    <br/>
    <br/>
    <br/>
    <h1><a href="{% url 'speech_bot:home' %}">Home</a> </h1>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
<form method="post">
    {% csrf_token %}
<input type="hidden" name="record">
<button class="button button5">Record</button>
</form>
<br/>
<br/>
<br/>
    <h1 style="color:red;"> {{data}}</h1>
    </center>
</body>
</html>