chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "chatbot"
urlpatterns = [
    path("home_bot", views.home, name='home'),
    path("speech_to_text/", views.speech_to_text, name='speech_to_text'),
 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

speech_bot/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "speech_bot"
urlpatterns = [
    path("home_bot", views.home, name='home'),
    path("speech_to_text/", views.speech_to_text, name='speech_to_text'),

 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views



app_name = "tutorial"
urlpatterns = [
    path('update/', views.pacient_create_view, name='website_update'),
    path('about/', views.about, name='website_about'),
    path('pacient_details/', views.pacient_general_form_view, name='website_general_form'),
    path('register/', views.registerPage, name='website_registerPage'),
    path('login/', views.loginPage, name='website_loginPage'),
    path('', views.index, name='website_index'),
    path('index/', views.index, name='website_index'),
    path('logout/', views.logoutPage, name='website_logoutPage'),
    path('mood/', views.MoodFormView, name='website_mood_form'),
    path('api/data/', views.get_data),
    path('results/', views.mood_results.as_view()),
    path('chartdata/', views.ChartDataAPI.as_view()),

 #   path('login/', LoginView.as_view(template_name='website/login.html'), name='website_login'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tutorial.urls')),
    path('',include('speech_bot.urls')),
]

templates/website/about.html
{% extends "website/base.html" %}
{% block content %}
    <h1>Ce putem face pentru tine?</h1>
    <p>If you’re concerned about whether an elderly relative or loved one is having trouble caring for themselves, it may be time to step in and offer some help. Before you start helping your loved one, take time to assess their needs. They may need assistance caring for their medical needs, or perhaps they could benefit from extra support during their day-to-day activities. If you aren’t able to care for them yourself, look for resources in your area such as assisted living facilities or in-home care services. Being a caregiver is challenging, so make sure to take time for your own needs as well! </p>
{% endblock content %}

templates/website/base.html
{% load static %}
{% load auth_extras %}
{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


<script src = 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'website/main.css' %}">

    {% if title %}
        <title>Virtual Assistant - {{ title }}</title>
    {% else %}
        <title>Virtual Assistant</title>
    {% endif %}
{% endblock %}

<body>


<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'tutorial:website_index' %}">Virtual Assistant</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'tutorial:website_index' %}">Acasa</a>
                    <a class="nav-item nav-link" href="{% url 'tutorial:website_about' %}">Despre</a>
                </div>
                <div class="navbar-nav">
                    <!-- Navbar Right Side -->
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'tutorial:website_logoutPage' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'tutorial:website_loginPage' %}">Login</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{% url 'tutorial:website_registerPage' %}">Inregistrare</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<div role="main" class="container">

    {% block content %}{% endblock %}

</div>


</body>

templates/website/index.html
{% load static %}
{% load auth_extras %}
{% block head %}
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Lobster&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Virtual Assistant - Un companion pentru cei la nevoie</title>

    <!-- Bootstrap core CSS -->

    <link href="{% static 'site_nou/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href="{% static 'site_nou/css/modern-business.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <style>
        .hello-msg{
            font-size: 18px;
            color: #fff;
            margin-right: 20px;
    }
    </style>
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'tutorial:website_index' %}">Virtual Assistant</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tutorial:website_about' %}">Despre proiect</a>
                    </li>
                    <li class="nav-item">
                        {% if not user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'tutorial:website_loginPage' %}">Login</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tutorial:website_registerPage' %}">Inregistrare</a>
                    </li>
                    {% endif %}
                    {% if request.user|has_group:"tutore" or request.user|has_group:"admin"%}
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'tutorial:website_update' %}">Insereaza pacient</a>
                    </li>
                    {% endif %}
                    {% if request.user|has_group:"pacient" or request.user|has_group:"admin"%}
                        {% if flag == True %}
                            {% if afectiune == 'alzheimer'%}
                                <li class="nav-item">
                                    <a class="nav-item nav-link" href="{% url 'tutorial:website_mood_form' %}">Chestionar Stare</a>
                                </li>
                            {% endif %}
                             {% if afectiune == 'depresie'%}
                                <li class="nav-item">
                                    <a class="nav-item nav-link" href="{% url 'tutorial:website_mood_form' %}">Chestionar Stare</a>
                                </li>
                            {% endif %}
                        {% endif %}
                        {% if flag == False %}
                            <li class="nav-item">
                                    <a class="nav-item nav-link" href="{% url 'tutorial:website_general_form' %}">Chestionar</a>
                            </li>
                        {% endif %}

                    {% endif %}
                    {% if request.user|has_group:"pacient" or request.user|has_group:"admin" %}
                            <li class="nav-item">
                                    <a class="nav-item nav-link" href="{% url 'speech_bot:home' %}">Chat Bot</a>
                            </li>
                        {% endif %}

                </ul>
            </div>
        </div>
    {% if user.is_authenticated %}
    <span class = "hello-msg">Buna, {{ request.user.username }}! </span>
    <span><a  class = "hello-msg" href="{% url 'tutorial:website_logoutPage' %}">Logout</a></span>
    {% endif %}
    </nav>

    <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div class="carousel-item active"
                     style="background-image: url('{% static 'images/img_slideshow_1.jpg' %}')">
                    <div class="carousel-caption d-none d-md-block">
                        <b><h1 style="color:whitesmoke; font-family: 'Chelsea Market', cursive;" >Avem grijă de tine</h1></b>
                        <b><h4 style="color:whitesmoke;font-family: 'Chelsea Market', cursive;" >Oriunde, oricând, suntem la un click distanță</h4></b>
                    </div>
                </div>
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('{% static 'images/img_slideshow_2.jpg' %}')">
                    <div class="carousel-caption d-none d-md-block">
                        <b><h2 style="color:ghostwhite; font-family: 'Chelsea Market', cursive;">Inteligența Artificială este viitorul</h2></b>
                        <b><h4 style="color:ghostwhite; font-family: 'Chelsea Market', cursive; ">Las-o să facă parte din viața ta !</h4></b>
                    </div>
                </div>
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <div class="carousel-item" style="background-image: url('{% static 'images/img_slideshow_3.jpg' %}')">
                    <div class="carousel-caption d-none d-md-block">
                        <b><h2 style="color:white; -webkit-text-stroke:0.25px black; font-family: 'Chelsea Market', cursive;">Lasă-te în baza Asistentului Virtual</h2></b>
                        <b><h4 style="color:white; -webkit-text-stroke: 0.25px black; font-family: 'Chelsea Market', cursive;">El se ajustează special pentru tine</h4></b>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <h1 class="my-4" align="center"  style="font-family: 'Indie Flower', cursive;">Bine ai venit la Asistentul Virtual !</h1>

        <!-- Portfolio Section -->
        <div class="row">
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top"  src="{% static 'images/alz.jpg' %}"  alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="#">Știai că...</a>
                        </h4>
                        <p class="card-text">Izolarea poate crește riscul de apariție a bolii Alzheimer?</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="{% static 'images/lonely.jpg' %}" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="#">Sau că...</a>
                        </h4>
                        <p class="card-text">Singurătatea e mai periculoasă decât obezitatea și la fel de dăunătoare cât
                        15 țigări pe zi?</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 portfolio-item">
                <div class="card h-100">
                    <a href="#"><img class="card-img-top" src="{% static 'images/heart_dis.jpg' %}" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="#">Dar și că....</a>
                        </h4>
                        <p class="card-text">Singurătatea duce la complicații ale inimii?</p>
                    </div>
                </div>
            </div>

        <!-- /.row -->

        <!-- Features Section -->
        <div class="row">
            <div class="col-lg-6">
                <h2>Cine suntem și ce facem?</h2>
                <p>Virtual Assistant este un proiect aflat în primul stadiu de cercetare și dezvoltare capabil să înlăture
                sentimentul se singurătate al utilizatorului. Lasă grija ta în seama noastră. Oferim servicii speciale
                pentru cei cu Alzheimer sau cei încercați de depresie și oferim rapoarte detaliate îngrijitorului cu privire
                la evoluția bolii. Câteva dintre funcțiile cheie sunt următoarele:</p>
                <ul>
                    <li>
                        <strong>Dialog intuitiv bazat pe concepte de inteligență artificială.</strong>
                    </li>
                    <li>Reîmprospătează-ți memoria adresând întrebări despre orice, iar Virtual Assisntant va reveni cu un răspuns.</li>
                    <li>Îți recomandă filme în baza filmului preferat</li>
                    <li>Nu uita nimic și programează-ți evenimentele în Google Calendar</li>
                    <li>Lasă-ne să te informăm cu știri de actualitate</li>
                    <li>Spune tot ce ai pe suflet și lasă-ne pe noi să-ți oferim sfaturi competente</li>
                    <li>Lasă-ne pe noi să căutăm informația inteligent pentru tine !</li>
                </ul>
                <strong><p>P.S Acest proiect nu reprezintă doar lucrarea de licență a mea, ci o soluție la o problemă cu care omenirea începe deja
                să se confunte ! Voi continua lucrul la acest proiect și după licență și îl voi duce la stadiul de producție</p></strong>
            </div>
            <div class="col-lg-6">
                <img class="img-fluid rounded" src="{% static 'images/team.jpg' %}" alt="">
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Section -->
        {% if request.user|has_group:"tutore" or request.user|has_group:"admin"%}
        <div class="row mb-4">
            <div class="col-md-8">
                <p>Pentru a începe lucrul cu Asistentul virtual, te rugăm să inserezi un pacient apăsând butonul din lateral</p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-secondary btn-block" href="{% url 'tutorial:website_update' %}">Începe acum</a>
            </div>
        </div>
         {% elif request.user|has_group:"pacient"%}
            <div class="row mb-4">
            <div class="col-md-8">
                <p>Asistentul virtual te așteaptă cu zâmbetul pe buze :). Apasă butonul din lateral pentru a începe</p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-secondary btn-block" href="{% url 'speech_bot:home' %}">Începe acum</a>
            </div>
        </div>
            {% else %}

            <div class="row mb-4">
            <div class="col-md-8">
                <p>Bună ! Te rugăm să te înregistrezi pentru a putea accesa oricare dintre aceste particularități</p>
            </div>
            <div class="col-md-4">
                <a class="btn btn-lg btn-secondary btn-block" href="{% url 'tutorial:website_registerPage' %}">Începe acum</a>
            </div>
            </div>
        {% endif %}

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Virtual Assistant 2020</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'site_nou/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'site_nou/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

{% endblock %}

templates/website/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		        {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'tutorial:website_registerPage' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/website/logout.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}
{% endblock content %}

templates/website/mood_form.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Buna !</h1>
    <form action='.' method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' value='Save'/>
        </form>
{% endblock %}

templates/website/pacient_general_form.html
{% extends 'website/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">

        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Hei! Vrem mai multe detalii despre tine.</legend>

                {{ form|crispy }}
                {{ form_disease|crispy }}
            </fieldset>
            <div class="form-roup">
                <button class="btn btn-outline-info" type="submit">Trimite</button>
            </div>
        </form>

    </div>
{% endblock content %}

templates/website/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Inregistrare</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Inregistrare cont</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                         {% csrf_token %}
                        <div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                                {{ form.first_name }}
						</div>
                        <div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                                {{ form.last_name }}
						</div>
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                                {{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
                                {{ form.email }}
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                                {{ form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                                {{ form.password2}}
						</div>


				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                {{ form.errors }}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Ai deja un cont? <a href="{% url 'tutorial:website_loginPage' %}" class="ml-2">Autentifica-te</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nume..';
		form_fields[2].placeholder='Prenume..';
		form_fields[3].placeholder='Username..';
		form_fields[4].placeholder='Email..';
		form_fields[5].placeholder='Enter password...';
		form_fields[6].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

templates/website/results.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Buna !</h1>
    <form action='.' method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' value='Save'/>
        </form>
{% endblock %}

templates/website/update.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.is_authenticated %}
        <h3>Bine ai venit, {{ request.user.username|title }} !</h3>

        {% if nr_pac >= 5 %}
            Ne pare rău, dar ai introdus deja 5 pacienți
        {% else %}
        Momentan ai inregistrati {{ nr_pac }} pacient(i) ! Poti avea maximum 5 pacienti<br><br>

        <form action='.' method='POST'>
            {% csrf_token %}

            {{ form_user|crispy }}
            {{ form|crispy }}
            <input type='submit' value='Save'/>
        </form>
        {% endif %}
    {% else %}
        <p>Nu esti logat ! Pentru a te loga, apasa pe link-ul de mai jos</p>
        <a href="{% url 'tutorial:website_loginPage' %}">login</a>
    {% endif %}
{% endblock content %}